# 첫 번째 풀이
# SELECT DATE_FORMAT(T.SALES_DATE, '%Y-%m-%d') SALES_DATE, T.PRODUCT_ID, T.USER_ID, T.SALES_AMOUNT
# FROM (SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
#       FROM ONLINE_SALE
#       UNION
#       SELECT SALES_DATE, PRODUCT_ID, NULL, SALES_AMOUNT
#       FROM OFFLINE_SALE) AS T
# WHERE T.SALES_DATE LIKE '2022-03%'
# ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;

# 두 번째 풀이
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE SALES_DATE LIKE '2022-03%'
UNION
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE SALES_DATE LIKE '2022-03%'
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;