WITH RAW AS (
    SELECT 
        A.CAR_ID,
        A.CAR_TYPE,
        A.DAILY_FEE,
        B.HISTORY_ID,
        B.START_DATE,
        B.END_DATE,
        DATEDIFF(B.END_DATE, B.START_DATE)+1 AS PERIOD,
        CASE
            WHEN DATEDIFF(B.END_DATE, B.START_DATE)+1 >= 7 AND DATEDIFF(B.END_DATE, B.START_DATE)+1 < 30 THEN '7일 이상' 
            WHEN  DATEDIFF(B.END_DATE, B.START_DATE)+1 >= 30 AND  DATEDIFF(B.END_DATE, B.START_DATE)+1 < 90 THEN '30일 이상'
            WHEN DATEDIFF(B.END_DATE, B.START_DATE)+1 >= 90 THEN '90일 이상'
            ELSE '기타' END PERIOD_TYPE
    FROM
        CAR_RENTAL_COMPANY_CAR A LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B 
        ON A.CAR_ID = B.CAR_ID 
    WHERE
        CAR_TYPE = "트럭"
)

SELECT 
    A.HISTORY_ID,
    FLOOR((A.DAILY_FEE * (100-COALESCE(B.DISCOUNT_RATE,0))/100) * A.PERIOD)AS FEE
FROM 
    RAW A LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B ON A.CAR_TYPE = B.CAR_TYPE AND A.PERIOD_TYPE = B.DURATION_TYPE
    ORDER BY FEE DESC, A.HISTORY_ID DESC