SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO AS I 
JOIN FISH_NAME_INFO AS N 
ON I.FISH_TYPE = N.FISH_TYPE
WHERE N.FISH_NAME IN ('BASS', 'SNAPPER');


# BASS, SNAPPER가 0,1이 아닐 수도 있다. 즉, 0,1로 찾는게 아니라 BASS, SNAPPER 이름으로 찾아야함.