-- 코드를 작성해주세요
SELECT A.ID , B.FISH_NAME, A.LENGTH
FROM FISH_INFO AS A LEFT JOIN FISH_NAME_INFO AS B ON A.FISH_TYPE = B.FISH_TYPE
WHERE A.LENGTH IN (SELECT MAX(LENGTH) 
                   FROM FISH_INFO AS F 
                   WHERE F.FISH_TYPE = A.FISH_TYPE 
                   GROUP BY F.FISH_TYPE)
AND LENGTH IS NOT NULL
ORDER BY A.ID;