WITH SUM_SCORE AS (
    SELECT EMP_NO
          ,SUM(SCORE) AS SCORE -- 사원별 상+하반기 점수 합산
    FROM HR_GRADE
    GROUP BY EMP_NO
), RANKING AS (
    SELECT EMP_NO
          ,SCORE
          ,DENSE_RANK() OVER (ORDER BY SCORE DESC) AS DR -- 점수에 순위 매기기 (중복 고려하여 DENSE_RANK 사용)
    FROM SUM_SCORE
)

SELECT RK.SCORE
      ,RK.EMP_NO
      ,HE.EMP_NAME
      ,HE.POSITION
      ,HE.EMAIL
FROM HR_EMPLOYEES HE
     INNER JOIN RANKING RK ON HE.EMP_NO = RK.EMP_NO
WHERE RK.DR = 1